copy new-em-fleet-maintenance-overview.png temp
copy em-fleet-maintenance-overview-2.png temp
copy new-em-fleet-maintenance-overview-2.png temp
copy patch.png temp
copy Target-Databases-Navig.png temp
copy new-software-std-advisor.png temp
copy generate-report.png temp
copy generate-report-confirmation.png temp
copy current-config.png temp
copy Homepage-SSA.png temp
copy open-office-msg.png temp
copy config-report.png temp 
copy workshop-instance.png temp
copy recommend-config.png temp 
copy recommend-report.png temp 
copy DB_Fleet_Patching.png temp
copy new-db-fleet-patching.png temp
copy patch-db-layout.png temp 
copy Launch-Hub.png temp 
copy Susbcribe-Hub.png temp 
copy Susbcribe-FinanceDB.png temp 
copy Subscribe-Close.png temp.png temp 
copy Tile3.png temp 
copy selection.png temp 
copy sales-patch-screen2.png temp 
copy submit-Validate.png temp 
copy quick-validate.png temp 
copy finance-validation-success.png temp 
copy finance-job-name.png temp 
copy finance-job-monitor.png temp 
copy DP.png temp 
copy deploy-complete.png temp 
copy uncheck-mig-listener.png temp
copy listener-migrate.png temp 
copy uncheck-update-db.png temp
copy patch-complete.png temp 
copy finance-post-upg-version.png temp 
copy finance-post-upg-tile3.png temp 
copy rollback-finance.png temp
copy 9091a9e1e04a1a988cb61d9171a483d.png temp
copy rollback-dp.png temp 
copy rollback-db-layout.png temp 
copy post-rollback-finance-update.png temp
copy e9091a9e1e04a1a988cb61d9171a483d.png temp
copy DP-submission-update.png temp.png temp
copy update-complete.png temp 
copy 038585c9308635261ae7e4aa956525af.png temp
copy new-finance-status.png temp 
copy cleanup-finance-report.png temp 
copy finance-cleanup-submission.png temp 
copy e9091a9e1e04a1a988cb61d9171a483d.png temp
copy cleanup-success-finance.png temp 
copy cleanup-sales-os-layout.png temp 
